"""Added new fields to user

Revision ID: 7e072b810836
Revises: 9c1f51acd52d
Create Date: 2024-03-17 14:46:12.756830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e072b810836'
down_revision: Union[str, None] = '9c1f51acd52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_column('users', 'status')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
